<br>

## Selected Presentations

<br>

* [**Antibody Characterization with Next Generation Sequencing (NGS) Using GroupMyAbs Shiny Application.**](GroupMyAbs_final.pdf)
Volha Tryputsen, Jocelyn Sendecki, Mark Tornetta.  
_Janssen Quantitative Sciences Annual Conference_ (poster, 2017)

* [**A Shiny App for Epitope Binning Analyses: High Throughput Analyses Made Easy.**](EpitopeBinning_Shiny_BRITE_poster_final.pdf)   
Volha Tryputsen, Jocelyn Sendecki, Robin Ernst, Sanjib Dutta, Joseph Bourghol, Annmarie Winkis, Fang Yi.  
_Janssen Quantitative Sciences Annual Conference_ (poster, 2017)  
_Janssen Biologics Research Innovation & Technology (BRITE) symposium_ (poster, 2016)  

* [**Optimizing Regions-of-Interest Composites for Capturing Treatment Effects on Brain Amyloid in Clinical Trials.**](imaging_biomarker_jsm_2014.pdf)   
Volha Tryputsen, Nandini Raghavan, Allitia DiBernardo.  
_Joint Statistical Meeting_ (contributed papers speaker, 2016).  
_FDA Industry Statistics Workshop_ (talk, 2014)  
_Alzheimer`s Association International Conference_ (poster, 2013)

* [**Development of a Serum Biomarker Panel to Predict Imminent Risk of Multiple Myeloma Progresssion.**](http://www.bloodjournal.org/content/122/21/3115?sso-checked=true)  
A. K. Sasser, T. Casneuf, V. Tryputsen, J. Werbeck, S. Kumar, S. V. Rajkumar, B. Hall. 
_American Society of Hematology Annual Meeting_ (poster, 2013)

* [**On the Selection of Cognitive and Functional Markers of Brain Volume and Atrophy**](http://www.alzheimersanddementia.com/article/S1552-5260(13)02272-3/abstract)  
Eric Yang, Nandini Raghavan, Volha Tryputsen, Michael Farnum, Victor Lobanov, Tim Schultz, Rudi Verbeeck, Mahesh N. Samtani, Gerald Novak, Vaibhav Narayan.  
_Alzheimer`s Association International Conference_ (poster, 2013)

* [**Using Fisher`s Method to Identify Enriched Gene Sets**](fishers_method_icsa_2012.pdf)
Volha Tryputsen, Javier Cabrera, An De Bond, Dhammika Amaratunga  
_International Chinese Statistical Association Symposium_ (talk, 2012)  

